version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_iot
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    expose:
      - 3000
    networks:
      - monitoring_network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - monitoring_network
  
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    expose:
      - 9091
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
